### ISSUE TITLE
Add Search Engine Optimization Meta Tags

### ISSUE THREAD

**Issue by jvillemare** [BITNULLS/storybook#100]
**Due Date:** Sprint S1

**Description:**
Add relevant SEO meta tags and files to our frontend and backend.

**Objectives:**
 - [x] Determine from client whether they want it publicly viewable on search engines, or totally private
 - [ ] Add OpenGraph meta tags, and basic search engine meta tags to our `index.html`
 - [ ] If needed, register the site with webmasters tools on Google, Bing, and such
