### ISSUE TITLE
Stale Branch Pruning (from previous Fall 2021) for New Semester

### ISSUE THREAD

**Issue by jvillemare** [BITNULLS/storybook#194]
**Due Date:** Sprint 6

**Description:**
We now have 70 branches.  Some are long dead (merged) and can be safely deleted.  This would be nice to cleanup our branch namespace.  

**Objectives:**
 - [ ] Identify every branch to delete, *EXCEPT* `main`, anything with an open PR, and anything newer than about two months (in case active work going on).
 - [ ] **Report it here**.
 - [ ] We'll discuss from there.
