### ISSUE TITLE
Use BFG to Clean Up Other Sensitive Files from Git History

### ISSUE THREAD

**Issue by jvillemare** [BITNULLS/storybook#201]
**Due Date:** Backlog

**Description:**
Remove the other sensitive files from `backend/data/` that were accidentally committed to the git history long ago.

BFG instructions:
- put it a directory above a repo, so ~/Projects/repo ? put the jar in ~/Projects/
- run java -jar bfg-1.14.0.jar --delete-files SENSITIVE_FILE repo (where repo should be the actual name of the folder that holds the repo
- cd into the repo
- git reflog expire --expire=now --all && git gc --prune=now --aggressive
- git push -f

**Objectives:**
 - [ ] Find the commits in the closed PRs that commited `backend/data/Wallet/` and such to the repository.
 - [ ] Remove with BFG.
 - [ ] Force commit update
