### ISSUE TITLE
Create Checklist for Database Updating

### ISSUE THREAD

**Issue by jvillemare** [BITNULLS/storybook#310]
**Due Date:** Sprint S3

**Description:**
To ensure proper and consistent procedures for handling database `enhancement`s and PRs, we should do like a lot of fields and come up with a checklist.

Framing device:  Whenever a new issue is created addressing a database update (new column, change table, etc), outline a procedure for exporting the DDL, updating the schema diagram, and such.

**Objectives:**
 - [x] Create a new file, `docs/checklists/database_updates.md`
 - [x] In that Markdown file, outline a checklist (using `- [ ]`; this create a checklist in Markdown) for
 - [x] ...exporting the DDL to `docs/499_Schema.sql`
 - [x] ...updating the `docs/Schema_Diagram.png`
 - [x] [Please do use proper Markdown formatting; Refresh with this link](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
 - [x] Make a PR
