### ISSUE TITLE
New GitHub Action to Run Unit Tests

### ISSUE THREAD

**Issue by jvillemare** [BITNULLS/storybook#359]
**Due Date:** Sprint S3

**Description:**
Make a new GitHub action that will run the unit tests on a pull requests open.

**Objectives:**
 - [x] Wait for #283 to finish
 - [ ] Make GitHub action
 - [ ] Make a PR
 - [ ] Wait for it to successfully pass on the PR
