### ISSUE TITLE
Email Verification Upon SignUp and Reset Password

### ISSUE THREAD

**Issue by mpatel-2022** [BITNULLS/storybook#44]
**Due Date:** Sprint 3

**Description:**
Once the user clicks sign up when they register, they receive an email with their logon information. When user resets password, they receive an email verification telling them their email has been reset. 

**Objectives:**
 - [ ] Initial registration verification email
 - [x] Password reset verification email 
 - [ ] Attach screenshots of here or in a PR of what they look like

**JIRA issue number:** To be filled in by @vivatheest
