### ISSUE TITLE
Deliver User Test Time Schedule to Client

### ISSUE THREAD

**Issue by jvillemare** [BITNULLS/storybook#454]
**Due Date:** Sprint S6

**Description:**
Finish time schedule spreadsheet and send it to client

**Objectives:**
 - [x] [Fill out spreadsheet](https://docs.google.com/spreadsheets/d/1ZLlLjCCru_Lz0UFfckZX-NPBWd9DV3n957lKNDFacd4/edit#gid=0)
 - [x] Send to client
 - [x] Close this issue
