### ISSUE TITLE
Add Sort Keyword to Action Data Export

### ISSUE THREAD

**Issue by jvillemare** [BITNULLS/storybook#455]
**Due Date:** Sprint S6

**Description:**
This is really simple and easy issue. The `action data download` button in the admin dashboard downloads the user action data. That action data is not sorted by date, and it should be.

**Objectives:**
 - [x] Figure out what query or procedure creates the action data export
 - [x] Add the `sort by action_start` clause to the query where appropriate
 - [x] Export DDL as according the database update checklist
 - [x] Make a PR
