### ISSUE TITLE
Finish Remaining User Tracking Actions Involving Q&A

### ISSUE THREAD

**Issue by lisapat** [BITNULLS/storybook#458]
**Due Date:** Sprint S6

**Description:**
Add remaining user tracking functions in tracker.js for user multiple choice & free response.

**Objectives:**
 - [x] Complete answered_question()
 - [x] Complete change_answer_question()
 - [x] Complete enter_text_response()
 - [x] Complete exit_text_response()
 - [ ] Complete click_link() (wait until the PNG slides have access to links)
